title: Веб-технологии
baseurl: "web-tech"
url: ""
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
lsi: false
safe: true
source: ./
incremental: false
highlighter: rouge
theme: minimal
