title: Веб-технологии
url: https://gosvoh.github.io
baseurl: /web-tech/
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
lsi: false
safe: true
incremental: false
highlighter: rouge
theme: jekyll-theme-minimal
