title: Веб-технологии
url: https://gosvoh.github.io
baseurl: /web-tech
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
lsi: false
safe: false
incremental: false
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
